
package com.ems.models.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Oct 04 11:46:48 IST 2021
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "getEmployeeResponse", namespace = "http://service.models.ems.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeeResponse", namespace = "http://service.models.ems.com/")

public class GetEmployeeResponse {

    @XmlElement(name = "return")
    private com.ems.models.Employee _return;

    public com.ems.models.Employee get_return() {
        return this._return;
    }
    
    public void set_return( com.ems.models.Employee new_return ) {
        this._return = new_return;
    }
    
}

