
package com.ems.models.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Oct 04 11:46:48 IST 2021
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "getEmployee", namespace = "http://service.models.ems.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployee", namespace = "http://service.models.ems.com/")

public class GetEmployee {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }
    
    public void setArg0( int newArg0 ) {
        this.arg0 = newArg0;
    }
    
}

